### ISSUE TITLE
About the Dataset

### ISSUE THREAD

**Issue by THE17** [SukonyaPhukan92/Image_Based_Air_Pollution_detection_using_InceptionV3_Model#1]
Can you please give us access to your Dataset ?

**Comment by SukonyaPhukan92** [comment]
Image Dataset link: https://drive.google.com/drive/folders/1bew6eW4ASIaWWhio5MovlAyeuvb_VYJe?usp=sharing

Code of Android Application: https://drive.google.com/file/d/17OuQ23v-UJYg42olZOxPvy9g95ptowQ6/view?usp=sharing
